// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ2hArwOuijX1bvrLwovpvWXiVsKoFF_s',
    appId: '1:551529753406:web:7f678ab0a031194e795a6f',
    messagingSenderId: '551529753406',
    projectId: 'todo-71494',
    authDomain: 'todo-71494.firebaseapp.com',
    storageBucket: 'todo-71494.appspot.com',
    measurementId: 'G-YCFW82DKW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOKNEv883TIr1_YcctCqdqkVGHem53osI',
    appId: '1:551529753406:android:5d08071967ebe170795a6f',
    messagingSenderId: '551529753406',
    projectId: 'todo-71494',
    storageBucket: 'todo-71494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC74JnWjuy9rcgzpuFB4k5W_h5zp6AbxCs',
    appId: '1:551529753406:ios:4f4458e90ec0ca9d795a6f',
    messagingSenderId: '551529753406',
    projectId: 'todo-71494',
    storageBucket: 'todo-71494.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC74JnWjuy9rcgzpuFB4k5W_h5zp6AbxCs',
    appId: '1:551529753406:ios:6b3a0a56fe33fc15795a6f',
    messagingSenderId: '551529753406',
    projectId: 'todo-71494',
    storageBucket: 'todo-71494.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
